[package]
name = "fdx"
version = "0.1.0"
edition = "2021"


[dependencies]
bls = { package = "ark-bls12-381", version = "0.4" }
ark-crypto-primitives = { version = "0.4", features = ["signature"] }
ark-ec = "0.4" 
ark-ff = "0.4" 
ark-std = "0.4"
