[package]
name = "fdx"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[features]
parallel = [
    # parallel feature is enabled by default
    #"ark-crypto-primitives/parallel",
    #"ark-ec/parallel",
    #"ark-ff/parallel",
    #"ark-poly/parallel",
    #"ark-poly-commit/parallel",
    #"ark-std/parallel",
    "rayon"
]

[dependencies]
ark-crypto-primitives = { version = "0.4", features = ["signature"] }
ark-ec = "0.4" 
ark-ff = "0.4" 
ark-poly = "0.4"
ark-poly-commit = "0.4"
ark-serialize = "0.4"
ark-std = "0.4"
digest = "0.10"
rayon = { version = "1.8", optional = true }

[dev-dependencies]
ark-bls12-381 = "0.4"
ark-secp256k1 = "0.4"
criterion = "0.5"
sha3 = "0.10"

#[[bench]]
#name = "elgamalkzg-backend"
#path = "benches/elgamalkzg.rs"
#harness = false

[[bench]]
name = "elgamalkzg-multi-backend"
path = "benches/elgamalkzg_multi.rs"
harness = false
